### ISSUE TITLE
无法在Fragment显示？

### ISSUE THREAD

**Issue by RXlung** [hugeterry/CoordinatorTabLayout#11]
测试在Fragment中使用的时候会有xml错误 android.view.InflateException: Binary XML file line #7: Error inflating class cn.hugeterry.coordinatortablayout.CoordinatorTabLayout
难道在Fragment中需要有啥特殊处理？
Activity中倒是可以显示
请教作者！！

**Comment by hugeterry** [comment]
你可以参照[这个项目的模块](https://github.com/xingkongus/jueqian/tree/master/app/src/main/java/us/xingkong/jueqian/module/RealS)
