### ISSUE TITLE
你好，我想问下这个怎么设置下拉不显示那个图片区域，望回复。

### ISSUE THREAD

**Issue by yangruixiang** [hugeterry/CoordinatorTabLayout#14]

**Comment by FollowMountain** [comment]
这个列子主要展示的就是头部拉伸收缩的特效，去掉这个就不用这个例子了。你要的是  tablayout+viewpager+fragment 的基础效果罢了~      这是andorid的基础，看看这篇文章吧：
http://blog.csdn.net/qq_33425116/article/details/52599818
