### ISSUE TITLE
关于不把状态栏隐藏达到沉浸式效果的问题

### ISSUE THREAD

**Issue by sweet2o09** [hugeterry/CoordinatorTabLayout#17]
你好,我看了下你的Demo,你是把状态栏隐藏起来了,这样达到了沉浸式的效果,
如果不隐藏状态栏,如何达到沉浸式效果呢?单一颜色还好说,可以直接改变状态栏的颜色,如果是图片呢,要如何做到沉浸式效果

**Comment by hugeterry** [comment]
新版本已增加该功能，请更新到1.1.0
```
dependencies {
    compile 'cn.hugeterry.coordinatortablayout:coordinatortablayout:1.1.0'
}
```

设置头部状态栏透明
`setTransulcentStatusBar(Activity activity)`:设置头部状态栏透明，在android4.4及以上版本生效
`mCoordinatorTabLayout.setTransulcentStatusBar(activity);`
