### ISSUE TITLE
头部的控件除了图片要是想加上其他的功能例如轮播图应该从那些方面修改

### ISSUE THREAD

**Issue by zengcanxiang** [hugeterry/CoordinatorTabLayout#2]
如题，谢谢

**Comment by hugeterry** [comment]
如果你是想从tab和viewpager之间添加，
```
<cn.hugeterry.coordinatortablayout.CoordinatorTabLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/coordinatortablayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    //将控件写在该地方
    <android.support.v4.view.ViewPager
        android:id="@+id/vp"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />
</cn.hugeterry.coordinatortablayout.CoordinatorTabLayout>
```
如果是想在imageview的地方插入，我不太知道你的需求，你可以把大致的线框图做给我看看，看是否能添加该需求，谢谢你的反馈

**Comment by zengcanxiang** [comment]
例如掌上英雄联盟客户端一样，和您的效果图除了imageview不一样之外，差不多都是一样的。

![screenshot_2017-02-09-12-41-13-0343834220](https://cloud.githubusercontent.com/assets/16033497/22769670/23f93cbe-eec5-11e6-9427-037b5fde85c0.png)

**Comment by hugeterry** [comment]
刚刚下载体验了一下，掌上英雄联盟客户端的XML结构跟这个库用的不一样
他应该没用到CoordinatorLayout，用了一个toolbar监听滚动，改变透明度
你可以用监听下面的recycleview的滚动，改变标题栏透明度就能实现它了

**Comment by zengcanxiang** [comment]
@hugeterry 是那个轮播广告在recycleview的滚动会往上，然后在到达toolbar高度的时候，不在变化。这个效果应该是与你的image效果是一致的。toolbar的透明度变化。。。。这个，额，没关注这个

**Comment by hugeterry** [comment]
做法不同，他这个效果是调用recycleview的addOnScrollListener，监听滚动，设置toolbar的透明度变化滴
