### ISSUE TITLE
关于底部状态栏的问题

### ISSUE THREAD

**Issue by lucky-you** [hugeterry/CoordinatorTabLayout#24]
下载了你的Demo,华为荣耀手机在7.0系统下，底部状态栏颜色出现了半透明的情况，看起来极不协调。

**Comment by hugeterry** [comment]
新版本已增加该功能，请更新到1.2.0

dependencies {
    compile 'cn.hugeterry.coordinatortablayout:coordinatortablayout:1.2.0'
}
设置头部状态栏透明
setTranslucentStatusBar(Activity activity):设置头部状态栏透明，在android4.4及以上版本生效
mCoordinatorTabLayout.setTranslucentStatusBar(activity);
