### ISSUE TITLE
请问如果fragment数量过多，怎么设置标题滑动显示？

### ISSUE THREAD

**Issue by afunnyrainman** [hugeterry/CoordinatorTabLayout#28]
请问如果fragment数量过多，怎么设置标题滑动显示？

**Comment by afunnyrainman** [comment]
我要自己在套一个tablayout？

**Comment by mavenjan** [comment]
需要自己重写setTabMode方法了。
/**
     * 设置TabMode
     *
     * @param mode 1
     * @return CoordinatorTabLayout
     */
    public CoordinatorTabLayout setTabMode(@TabLayout.Mode int mode) {
        mTabLayout.setTabMode(mode);
        return this;
    }
初始化时调用
 mCoordinatorTabLayout.setTranslucentStatusBar(this)
                .setTitle("Demo")
                .setBackEnable(true)
                .setTabMode(TabLayout.MODE_SCROLLABLE)
                .setImageArray(mImageArray, mColorArray)
                .setupWithViewPager(mViewPager);

PS:建议作者把tablayout的常用方法在CoordinatorTabLayout.class里重写一下，以便调用。 谢谢分享

**Comment by hugeterry** [comment]
@afunnyrainman 现版本已有`getTabLayout()`:get the TabLayout 可自行对tablayout进行修改
感谢@mavenjan 已commit，新版本会加入该方法

**Comment by afunnyrainman** [comment]
好的，感谢

**Comment by hugeterry** [comment]
已在1.2.2中加上该方法，可直接调用`setTabMode`
