### ISSUE TITLE
Load header image from network

### ISSUE THREAD

**Issue by rajeevjaiswal** [hugeterry/CoordinatorTabLayout#3]
Is it possible to load header images using picasso/glide etc

**Comment by pingL** [comment]
基本栗子这样就挺好的，你说的顶部图片加载什么的自己可以随意扩展。

**Comment by hugeterry** [comment]
Upgrade to version  1.0.6
There is a [sample](https://github.com/hugeterry/CoordinatorTabLayout/blob/master/sample/src/main/java/cn/hugeterry/coordinatortablayoutdemo/LoadHeaderImageFromNetworkActivity.java) provided which shows how to use the library load header images using glide.
Thank you
