### ISSUE TITLE
java.lang.NoSuchMethodError---addOnTabSelectedListener

### ISSUE THREAD

**Issue by CavellChance** [hugeterry/CoordinatorTabLayout#41]
我在项目中使用你的实例代码运行，直接闪退编译器报错：java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.QianLiu.ilovedu-V7nBu3dS_MihIsRFOxzOIQ==/split_lib_dependencies_apk.apk)
我的gradle配置如下：
 buildToolsVersion = '28.0.3'

  implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'

我尝试改变build库的版本，没能解决，请问你这边有没有解决的思路，谢谢

**Comment by peterMa1999** [comment]
我的也是这个错

**Comment by CavellChance** [comment]
> 我的也是这个错

一般方法找不到，多是因为引用的包不对
