### ISSUE TITLE
About status bar

### ISSUE THREAD

**Issue by lyrachord** [hugeterry/CoordinatorTabLayout#5]
Hi,

Checking out the demo, it's a full screen mode. I guess there is a question:
Are you sure it's the result by design?
Or I missed something?

Cheers

**Comment by hugeterry** [comment]
It‘s ok.
You can set the status bar by yourself.
Thank you

**Comment by GitHubAFeng** [comment]
你好，请问怎么实现自己的Toolbar，直接修改源码中的view_coordinatortablayout布局文件吗？还是有更好的办法呢？

**Comment by hugeterry** [comment]
@GitHubAFeng 可以通过`getActionBar()`对Toolbar进行修改
不清楚你的具体需求，你可以说说我看看对其进行新增接口

**Comment by xiaoerMr** [comment]
Failed to resolve: com.android.support:appcompat-v7:25.1.0
Failed to resolve: com.android.support:design:25.1.0
这两个下载报错,怎么办

**Comment by hugeterry** [comment]
@xiaoerMr 请自行添加相应版本的sdk

**Comment by xiaoerMr** [comment]
我有这个版本的sdk 而且
com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1' 这个俩个可以使用,这是为什么
