### ISSUE TITLE
如果tab太多怎么办

### ISSUE THREAD

**Issue by zhengmingliang** [hugeterry/CoordinatorTabLayout#9]
![image](https://cloud.githubusercontent.com/assets/16442564/24704099/bf3da75c-1a38-11e7-8d20-2745b3cb230c.png)
* 当tab设置的太多的时候，文字就会显示不全
* 如果有多个tab，添加的图片数组和颜色数组的大小必需和tab一致，不能共用同一颜色或者同一图片么

**Comment by hugeterry** [comment]
`getTabLayout():get the TabLayout`可以拿到tablayout，
调用`getTabLayout().setTabMode(TabLayout.MODE_SCROLLABLE);`将`tablayout`是设置成滑动即可
